### ISSUE TITLE
No tags in prompt under Auto1111

### ISSUE THREAD

**Issue by mykeehu** [EnsignMK/danbooru-prompt#1]
I have a problem under Automatic1111, version 1.4.1 (the latest release): I paste the link, press the button and nothing happens, the prompt remains blank. But it works in Vladmandic (SD.Next). What could be the problem under Automatic release?

**Comment by EnsignMK** [comment]
To give you some context ,When I developed this , I was using an older version of the SD Automatic ,perhaps an compatibility issue,  I  will look into it , I will let you know what I find , thanks for reporting it

**Comment by EnsignMK** [comment]
Can you provide me an example link that doesn't work? @mykeehu 
I Installed the latest version 1.4.1 and I tried some links.
Example: https://danbooru.donmai.us/posts/6503608 ,it works 

perhaps you put a wrong kind of link.

**Comment by EnsignMK** [comment]
I updated the extension ,it will show you in the textbox when you put  an wrong  url.
![image](https://github.com/EnsignMK/danbooru-prompt/assets/91480302/1e2cd615-da1d-4a50-a007-93c701c6a6cb)

Let me know if this helped.

**Comment by mykeehu** [comment]
The link is fine, I just checked yours. Maybe it's incompatible with one of the other add-ons (I use quite a few), because I put the link in, press the button, the prompt box flashes, then doesn't put it in. That's how I use the prompt:
![image](https://github.com/EnsignMK/danbooru-prompt/assets/6390413/6076abe7-d535-4d85-b7c4-66eb0149057b)

**Comment by EnsignMK** [comment]
"Maybe it's incompatible with one of the other add-ons"  it must be , what kind of add on is on that image? @mykeehu

**Comment by mykeehu** [comment]
I am currently using these extensions. I don't know which one has to do with the prompt insertion.
![image](https://github.com/EnsignMK/danbooru-prompt/assets/6390413/2b0973ce-6f55-4e00-80c6-d6bb7699e270)

**Comment by EnsignMK** [comment]
So here what you can do , disable 1 extension at the time  and check if danbooru-prompt works,
if it works ,you found the culprit and you can share the name of the extension ,I then will make sure that these two extension will work nicely together.   Out of curiousity does  sd-webui-gelbooru-prompt work for you? it's similair to my extension.

**Comment by mykeehu** [comment]
The sd-webui-gelbooru-prompt works for me, at least it gets the prompt in its own window based on the downloaded image. I'm using this method now until I can't use the danbooru-prompt.

**Comment by mykeehu** [comment]
This is getting more interesting. Because I have only enabled the danbooruu extension and it still does not put the text in the prompt.
![image](https://github.com/EnsignMK/danbooru-prompt/assets/6390413/131c3885-56fe-4e1b-a6b4-21bde13a916f)

By the way, I see an error like this in the command prompt, which could be auto1111 or gradio error, it's independent of the danbooruu extension:

```
H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\inputs.py:89: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py:871: UserWarning: `optional` parameter is deprecated, and it has no effect
  IOComponent.__init__(
H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\inputs.py:121: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py:1037: UserWarning: `optional` parameter is deprecated, and it has no effect
  IOComponent.__init__(
Running on local URL:  http://127.0.0.1:7860
```

**Comment by EnsignMK** [comment]
So let's try this , find the extension folder ,locate the danbooru-prompt folder  and delete the  danbooru-prompt folder.
afterwards restart the sd web ui.

I made a new github branch that alters the code slightly.
<img width="407" alt="image" src="https://github.com/EnsignMK/danbooru-prompt/assets/91480302/cfca9e49-27e5-478a-ad4d-ef15ab06d1f1">

install this and let me know if this works for you.

url=https://github.com/EnsignMK/danbooru-prompt.git
Specific branch name= debug_branch

if every everything works correctly you'll see this:
<img width="553" alt="image" src="https://github.com/EnsignMK/danbooru-prompt/assets/91480302/8e25ccd9-e8e4-49d7-910f-b27767ff9dc8">

**Comment by mykeehu** [comment]
Interesting. I'll show you that it doesn't give me the prompt here either. I don't understand why you refuse. The same happened with the prompt with older version.

![Stable_Diffusion_-_Google_Chrome-2023-07-20-22-19-47](https://github.com/EnsignMK/danbooru-prompt/assets/6390413/8ab8e7a4-b2ee-423b-92a2-c109dd3ac421)

**Comment by EnsignMK** [comment]
I don't know what's going on,I tried this on google collab and it works  ,I am seeing what you send me,  maybe as last resort ,check if   beautifulsoup4 is installed,
try pip install  beautifulsoup4

**Comment by mykeehu** [comment]
I reinstalled it, but it didn't help. I have a local installation, yes, and I don't understand it because Gelbooru works. So I use that, only the Danbooruu version would have been better because then I don't have to download the image.

**Comment by EnsignMK** [comment]
@mykeehu  Thanks for trying , there is a good alternative for you: 
another sd extension ,it should work you out of the box. You don;t need an api ,
https://github.com/Malisius/booru2prompt

<img width="1159" alt="image" src="https://github.com/EnsignMK/danbooru-prompt/assets/91480302/0ebeed92-c14d-4ade-bfa7-6c89dcb1622c">

cheers

**Comment by mykeehu** [comment]
I just tried the latter and it absolutely works! Thank you very much for the idea and the supplement!
